### ISSUE TITLE
ASIO401 doesn't read toml file or enter any data in log file

### ISSUE THREAD

**Issue by pt10055** [dechamps/ASIO401#22]
I have created both in my user directory.  Verified the toml file is readable with the 'type' command.  I launch the QA401 app first, then quit.  Then launch another ASIO app, the hardware works but settings in the toml file are ignored.  Trying to reset the attenuator, it's always on. 

I haven't seen anything show up in the log file.

**Comment by dechamps** [comment]
So you're saying that ASIO401 does work, but it doesn't seem to read the `ASIO401.toml` file and doesn't seem to be writing anything to `ASIO401.log`?

That's surprising. Let's focus on the logfile first, because it's difficult to troubleshoot a configuration issue without that.

Just to make sure, could you please open a command line and paste the result of the following command:

```
dir %userprofile%\ASIO401*
```

**Comment by pt10055** [comment]
OK, thanks.  I'm an idiot.  Logged in under the wrong profile.  Works fine now.
